version: '3.1'

services:
  app:
    depends_on: 
      - mysql-docker
    build: .

  mysql-docker:
    image: mysql
    restart: always
    ports:
    - 3307:3306
    environment: 
      MYSQL_ROOT_PASSWORD: myexamplepassword