version: '3.1'

services:
  mysql-docker:
    image: mysql
    restart: always
    ports:
    - 3307:3306
    environment: 
      MYSQL_ROOT_PASSWORD: myexamplepassword
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9000:80
    environment: 
      - PMA_ARBITRARY=1